// Generated from the IANA time zone database zone.tab (public domain).
window.TIME_ZONES = Object.freeze([
  Object.freeze({ country: "AD", zone: "Europe/Andorra" }),
  Object.freeze({ country: "AE", zone: "Asia/Dubai" }),
  Object.freeze({ country: "AF", zone: "Asia/Kabul" }),
  Object.freeze({ country: "AG", zone: "America/Antigua" }),
  Object.freeze({ country: "AI", zone: "America/Anguilla" }),
  Object.freeze({ country: "AL", zone: "Europe/Tirane" }),
  Object.freeze({ country: "AM", zone: "Asia/Yerevan" }),
  Object.freeze({ country: "AO", zone: "Africa/Luanda" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/McMurdo" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Casey" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Davis" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/DumontDUrville" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Mawson" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Palmer" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Rothera" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Syowa" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Troll" }),
  Object.freeze({ country: "AQ", zone: "Antarctica/Vostok" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Buenos_Aires" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Cordoba" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Salta" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Jujuy" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Tucuman" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Catamarca" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/La_Rioja" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/San_Juan" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Mendoza" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/San_Luis" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Rio_Gallegos" }),
  Object.freeze({ country: "AR", zone: "America/Argentina/Ushuaia" }),
  Object.freeze({ country: "AS", zone: "Pacific/Pago_Pago" }),
  Object.freeze({ country: "AT", zone: "Europe/Vienna" }),
  Object.freeze({ country: "AU", zone: "Australia/Lord_Howe" }),
  Object.freeze({ country: "AU", zone: "Antarctica/Macquarie" }),
  Object.freeze({ country: "AU", zone: "Australia/Hobart" }),
  Object.freeze({ country: "AU", zone: "Australia/Melbourne" }),
  Object.freeze({ country: "AU", zone: "Australia/Sydney" }),
  Object.freeze({ country: "AU", zone: "Australia/Broken_Hill" }),
  Object.freeze({ country: "AU", zone: "Australia/Brisbane" }),
  Object.freeze({ country: "AU", zone: "Australia/Lindeman" }),
  Object.freeze({ country: "AU", zone: "Australia/Adelaide" }),
  Object.freeze({ country: "AU", zone: "Australia/Darwin" }),
  Object.freeze({ country: "AU", zone: "Australia/Perth" }),
  Object.freeze({ country: "AU", zone: "Australia/Eucla" }),
  Object.freeze({ country: "AW", zone: "America/Aruba" }),
  Object.freeze({ country: "AX", zone: "Europe/Mariehamn" }),
  Object.freeze({ country: "AZ", zone: "Asia/Baku" }),
  Object.freeze({ country: "BA", zone: "Europe/Sarajevo" }),
  Object.freeze({ country: "BB", zone: "America/Barbados" }),
  Object.freeze({ country: "BD", zone: "Asia/Dhaka" }),
  Object.freeze({ country: "BE", zone: "Europe/Brussels" }),
  Object.freeze({ country: "BF", zone: "Africa/Ouagadougou" }),
  Object.freeze({ country: "BG", zone: "Europe/Sofia" }),
  Object.freeze({ country: "BH", zone: "Asia/Bahrain" }),
  Object.freeze({ country: "BI", zone: "Africa/Bujumbura" }),
  Object.freeze({ country: "BJ", zone: "Africa/Porto-Novo" }),
  Object.freeze({ country: "BL", zone: "America/St_Barthelemy" }),
  Object.freeze({ country: "BM", zone: "Atlantic/Bermuda" }),
  Object.freeze({ country: "BN", zone: "Asia/Brunei" }),
  Object.freeze({ country: "BO", zone: "America/La_Paz" }),
  Object.freeze({ country: "BQ", zone: "America/Kralendijk" }),
  Object.freeze({ country: "BR", zone: "America/Noronha" }),
  Object.freeze({ country: "BR", zone: "America/Belem" }),
  Object.freeze({ country: "BR", zone: "America/Fortaleza" }),
  Object.freeze({ country: "BR", zone: "America/Recife" }),
  Object.freeze({ country: "BR", zone: "America/Araguaina" }),
  Object.freeze({ country: "BR", zone: "America/Maceio" }),
  Object.freeze({ country: "BR", zone: "America/Bahia" }),
  Object.freeze({ country: "BR", zone: "America/Sao_Paulo" }),
  Object.freeze({ country: "BR", zone: "America/Campo_Grande" }),
  Object.freeze({ country: "BR", zone: "America/Cuiaba" }),
  Object.freeze({ country: "BR", zone: "America/Santarem" }),
  Object.freeze({ country: "BR", zone: "America/Porto_Velho" }),
  Object.freeze({ country: "BR", zone: "America/Boa_Vista" }),
  Object.freeze({ country: "BR", zone: "America/Manaus" }),
  Object.freeze({ country: "BR", zone: "America/Eirunepe" }),
  Object.freeze({ country: "BR", zone: "America/Rio_Branco" }),
  Object.freeze({ country: "BS", zone: "America/Nassau" }),
  Object.freeze({ country: "BT", zone: "Asia/Thimphu" }),
  Object.freeze({ country: "BW", zone: "Africa/Gaborone" }),
  Object.freeze({ country: "BY", zone: "Europe/Minsk" }),
  Object.freeze({ country: "BZ", zone: "America/Belize" }),
  Object.freeze({ country: "CA", zone: "America/St_Johns" }),
  Object.freeze({ country: "CA", zone: "America/Halifax" }),
  Object.freeze({ country: "CA", zone: "America/Glace_Bay" }),
  Object.freeze({ country: "CA", zone: "America/Moncton" }),
  Object.freeze({ country: "CA", zone: "America/Goose_Bay" }),
  Object.freeze({ country: "CA", zone: "America/Blanc-Sablon" }),
  Object.freeze({ country: "CA", zone: "America/Toronto" }),
  Object.freeze({ country: "CA", zone: "America/Iqaluit" }),
  Object.freeze({ country: "CA", zone: "America/Atikokan" }),
  Object.freeze({ country: "CA", zone: "America/Winnipeg" }),
  Object.freeze({ country: "CA", zone: "America/Resolute" }),
  Object.freeze({ country: "CA", zone: "America/Rankin_Inlet" }),
  Object.freeze({ country: "CA", zone: "America/Regina" }),
  Object.freeze({ country: "CA", zone: "America/Swift_Current" }),
  Object.freeze({ country: "CA", zone: "America/Edmonton" }),
  Object.freeze({ country: "CA", zone: "America/Cambridge_Bay" }),
  Object.freeze({ country: "CA", zone: "America/Inuvik" }),
  Object.freeze({ country: "CA", zone: "America/Creston" }),
  Object.freeze({ country: "CA", zone: "America/Dawson_Creek" }),
  Object.freeze({ country: "CA", zone: "America/Fort_Nelson" }),
  Object.freeze({ country: "CA", zone: "America/Whitehorse" }),
  Object.freeze({ country: "CA", zone: "America/Dawson" }),
  Object.freeze({ country: "CA", zone: "America/Vancouver" }),
  Object.freeze({ country: "CC", zone: "Indian/Cocos" }),
  Object.freeze({ country: "CD", zone: "Africa/Kinshasa" }),
  Object.freeze({ country: "CD", zone: "Africa/Lubumbashi" }),
  Object.freeze({ country: "CF", zone: "Africa/Bangui" }),
  Object.freeze({ country: "CG", zone: "Africa/Brazzaville" }),
  Object.freeze({ country: "CH", zone: "Europe/Zurich" }),
  Object.freeze({ country: "CI", zone: "Africa/Abidjan" }),
  Object.freeze({ country: "CK", zone: "Pacific/Rarotonga" }),
  Object.freeze({ country: "CL", zone: "America/Santiago" }),
  Object.freeze({ country: "CL", zone: "America/Coyhaique" }),
  Object.freeze({ country: "CL", zone: "America/Punta_Arenas" }),
  Object.freeze({ country: "CL", zone: "Pacific/Easter" }),
  Object.freeze({ country: "CM", zone: "Africa/Douala" }),
  Object.freeze({ country: "CN", zone: "Asia/Shanghai" }),
  Object.freeze({ country: "CN", zone: "Asia/Urumqi" }),
  Object.freeze({ country: "CO", zone: "America/Bogota" }),
  Object.freeze({ country: "CR", zone: "America/Costa_Rica" }),
  Object.freeze({ country: "CU", zone: "America/Havana" }),
  Object.freeze({ country: "CV", zone: "Atlantic/Cape_Verde" }),
  Object.freeze({ country: "CW", zone: "America/Curacao" }),
  Object.freeze({ country: "CX", zone: "Indian/Christmas" }),
  Object.freeze({ country: "CY", zone: "Asia/Nicosia" }),
  Object.freeze({ country: "CY", zone: "Asia/Famagusta" }),
  Object.freeze({ country: "CZ", zone: "Europe/Prague" }),
  Object.freeze({ country: "DE", zone: "Europe/Berlin" }),
  Object.freeze({ country: "DE", zone: "Europe/Busingen" }),
  Object.freeze({ country: "DJ", zone: "Africa/Djibouti" }),
  Object.freeze({ country: "DK", zone: "Europe/Copenhagen" }),
  Object.freeze({ country: "DM", zone: "America/Dominica" }),
  Object.freeze({ country: "DO", zone: "America/Santo_Domingo" }),
  Object.freeze({ country: "DZ", zone: "Africa/Algiers" }),
  Object.freeze({ country: "EC", zone: "America/Guayaquil" }),
  Object.freeze({ country: "EC", zone: "Pacific/Galapagos" }),
  Object.freeze({ country: "EE", zone: "Europe/Tallinn" }),
  Object.freeze({ country: "EG", zone: "Africa/Cairo" }),
  Object.freeze({ country: "EH", zone: "Africa/El_Aaiun" }),
  Object.freeze({ country: "ER", zone: "Africa/Asmara" }),
  Object.freeze({ country: "ES", zone: "Europe/Madrid" }),
  Object.freeze({ country: "ES", zone: "Africa/Ceuta" }),
  Object.freeze({ country: "ES", zone: "Atlantic/Canary" }),
  Object.freeze({ country: "ET", zone: "Africa/Addis_Ababa" }),
  Object.freeze({ country: "FI", zone: "Europe/Helsinki" }),
  Object.freeze({ country: "FJ", zone: "Pacific/Fiji" }),
  Object.freeze({ country: "FK", zone: "Atlantic/Stanley" }),
  Object.freeze({ country: "FM", zone: "Pacific/Chuuk" }),
  Object.freeze({ country: "FM", zone: "Pacific/Pohnpei" }),
  Object.freeze({ country: "FM", zone: "Pacific/Kosrae" }),
  Object.freeze({ country: "FO", zone: "Atlantic/Faroe" }),
  Object.freeze({ country: "FR", zone: "Europe/Paris" }),
  Object.freeze({ country: "GA", zone: "Africa/Libreville" }),
  Object.freeze({ country: "GB", zone: "Europe/London" }),
  Object.freeze({ country: "GD", zone: "America/Grenada" }),
  Object.freeze({ country: "GE", zone: "Asia/Tbilisi" }),
  Object.freeze({ country: "GF", zone: "America/Cayenne" }),
  Object.freeze({ country: "GG", zone: "Europe/Guernsey" }),
  Object.freeze({ country: "GH", zone: "Africa/Accra" }),
  Object.freeze({ country: "GI", zone: "Europe/Gibraltar" }),
  Object.freeze({ country: "GL", zone: "America/Nuuk" }),
  Object.freeze({ country: "GL", zone: "America/Danmarkshavn" }),
  Object.freeze({ country: "GL", zone: "America/Scoresbysund" }),
  Object.freeze({ country: "GL", zone: "America/Thule" }),
  Object.freeze({ country: "GM", zone: "Africa/Banjul" }),
  Object.freeze({ country: "GN", zone: "Africa/Conakry" }),
  Object.freeze({ country: "GP", zone: "America/Guadeloupe" }),
  Object.freeze({ country: "GQ", zone: "Africa/Malabo" }),
  Object.freeze({ country: "GR", zone: "Europe/Athens" }),
  Object.freeze({ country: "GS", zone: "Atlantic/South_Georgia" }),
  Object.freeze({ country: "GT", zone: "America/Guatemala" }),
  Object.freeze({ country: "GU", zone: "Pacific/Guam" }),
  Object.freeze({ country: "GW", zone: "Africa/Bissau" }),
  Object.freeze({ country: "GY", zone: "America/Guyana" }),
  Object.freeze({ country: "HK", zone: "Asia/Hong_Kong" }),
  Object.freeze({ country: "HN", zone: "America/Tegucigalpa" }),
  Object.freeze({ country: "HR", zone: "Europe/Zagreb" }),
  Object.freeze({ country: "HT", zone: "America/Port-au-Prince" }),
  Object.freeze({ country: "HU", zone: "Europe/Budapest" }),
  Object.freeze({ country: "ID", zone: "Asia/Jakarta" }),
  Object.freeze({ country: "ID", zone: "Asia/Pontianak" }),
  Object.freeze({ country: "ID", zone: "Asia/Makassar" }),
  Object.freeze({ country: "ID", zone: "Asia/Jayapura" }),
  Object.freeze({ country: "IE", zone: "Europe/Dublin" }),
  Object.freeze({ country: "IL", zone: "Asia/Jerusalem" }),
  Object.freeze({ country: "IM", zone: "Europe/Isle_of_Man" }),
  Object.freeze({ country: "IN", zone: "Asia/Kolkata" }),
  Object.freeze({ country: "IO", zone: "Indian/Chagos" }),
  Object.freeze({ country: "IQ", zone: "Asia/Baghdad" }),
  Object.freeze({ country: "IR", zone: "Asia/Tehran" }),
  Object.freeze({ country: "IS", zone: "Atlantic/Reykjavik" }),
  Object.freeze({ country: "IT", zone: "Europe/Rome" }),
  Object.freeze({ country: "JE", zone: "Europe/Jersey" }),
  Object.freeze({ country: "JM", zone: "America/Jamaica" }),
  Object.freeze({ country: "JO", zone: "Asia/Amman" }),
  Object.freeze({ country: "JP", zone: "Asia/Tokyo" }),
  Object.freeze({ country: "KE", zone: "Africa/Nairobi" }),
  Object.freeze({ country: "KG", zone: "Asia/Bishkek" }),
  Object.freeze({ country: "KH", zone: "Asia/Phnom_Penh" }),
  Object.freeze({ country: "KI", zone: "Pacific/Tarawa" }),
  Object.freeze({ country: "KI", zone: "Pacific/Kanton" }),
  Object.freeze({ country: "KI", zone: "Pacific/Kiritimati" }),
  Object.freeze({ country: "KM", zone: "Indian/Comoro" }),
  Object.freeze({ country: "KN", zone: "America/St_Kitts" }),
  Object.freeze({ country: "KP", zone: "Asia/Pyongyang" }),
  Object.freeze({ country: "KR", zone: "Asia/Seoul" }),
  Object.freeze({ country: "KW", zone: "Asia/Kuwait" }),
  Object.freeze({ country: "KY", zone: "America/Cayman" }),
  Object.freeze({ country: "KZ", zone: "Asia/Almaty" }),
  Object.freeze({ country: "KZ", zone: "Asia/Qyzylorda" }),
  Object.freeze({ country: "KZ", zone: "Asia/Qostanay" }),
  Object.freeze({ country: "KZ", zone: "Asia/Aqtobe" }),
  Object.freeze({ country: "KZ", zone: "Asia/Aqtau" }),
  Object.freeze({ country: "KZ", zone: "Asia/Atyrau" }),
  Object.freeze({ country: "KZ", zone: "Asia/Oral" }),
  Object.freeze({ country: "LA", zone: "Asia/Vientiane" }),
  Object.freeze({ country: "LB", zone: "Asia/Beirut" }),
  Object.freeze({ country: "LC", zone: "America/St_Lucia" }),
  Object.freeze({ country: "LI", zone: "Europe/Vaduz" }),
  Object.freeze({ country: "LK", zone: "Asia/Colombo" }),
  Object.freeze({ country: "LR", zone: "Africa/Monrovia" }),
  Object.freeze({ country: "LS", zone: "Africa/Maseru" }),
  Object.freeze({ country: "LT", zone: "Europe/Vilnius" }),
  Object.freeze({ country: "LU", zone: "Europe/Luxembourg" }),
  Object.freeze({ country: "LV", zone: "Europe/Riga" }),
  Object.freeze({ country: "LY", zone: "Africa/Tripoli" }),
  Object.freeze({ country: "MA", zone: "Africa/Casablanca" }),
  Object.freeze({ country: "MC", zone: "Europe/Monaco" }),
  Object.freeze({ country: "MD", zone: "Europe/Chisinau" }),
  Object.freeze({ country: "ME", zone: "Europe/Podgorica" }),
  Object.freeze({ country: "MF", zone: "America/Marigot" }),
  Object.freeze({ country: "MG", zone: "Indian/Antananarivo" }),
  Object.freeze({ country: "MH", zone: "Pacific/Majuro" }),
  Object.freeze({ country: "MH", zone: "Pacific/Kwajalein" }),
  Object.freeze({ country: "MK", zone: "Europe/Skopje" }),
  Object.freeze({ country: "ML", zone: "Africa/Bamako" }),
  Object.freeze({ country: "MM", zone: "Asia/Yangon" }),
  Object.freeze({ country: "MN", zone: "Asia/Ulaanbaatar" }),
  Object.freeze({ country: "MN", zone: "Asia/Hovd" }),
  Object.freeze({ country: "MO", zone: "Asia/Macau" }),
  Object.freeze({ country: "MP", zone: "Pacific/Saipan" }),
  Object.freeze({ country: "MQ", zone: "America/Martinique" }),
  Object.freeze({ country: "MR", zone: "Africa/Nouakchott" }),
  Object.freeze({ country: "MS", zone: "America/Montserrat" }),
  Object.freeze({ country: "MT", zone: "Europe/Malta" }),
  Object.freeze({ country: "MU", zone: "Indian/Mauritius" }),
  Object.freeze({ country: "MV", zone: "Indian/Maldives" }),
  Object.freeze({ country: "MW", zone: "Africa/Blantyre" }),
  Object.freeze({ country: "MX", zone: "America/Mexico_City" }),
  Object.freeze({ country: "MX", zone: "America/Cancun" }),
  Object.freeze({ country: "MX", zone: "America/Merida" }),
  Object.freeze({ country: "MX", zone: "America/Monterrey" }),
  Object.freeze({ country: "MX", zone: "America/Matamoros" }),
  Object.freeze({ country: "MX", zone: "America/Chihuahua" }),
  Object.freeze({ country: "MX", zone: "America/Ciudad_Juarez" }),
  Object.freeze({ country: "MX", zone: "America/Ojinaga" }),
  Object.freeze({ country: "MX", zone: "America/Mazatlan" }),
  Object.freeze({ country: "MX", zone: "America/Bahia_Banderas" }),
  Object.freeze({ country: "MX", zone: "America/Hermosillo" }),
  Object.freeze({ country: "MX", zone: "America/Tijuana" }),
  Object.freeze({ country: "MY", zone: "Asia/Kuala_Lumpur" }),
  Object.freeze({ country: "MY", zone: "Asia/Kuching" }),
  Object.freeze({ country: "MZ", zone: "Africa/Maputo" }),
  Object.freeze({ country: "NA", zone: "Africa/Windhoek" }),
  Object.freeze({ country: "NC", zone: "Pacific/Noumea" }),
  Object.freeze({ country: "NE", zone: "Africa/Niamey" }),
  Object.freeze({ country: "NF", zone: "Pacific/Norfolk" }),
  Object.freeze({ country: "NG", zone: "Africa/Lagos" }),
  Object.freeze({ country: "NI", zone: "America/Managua" }),
  Object.freeze({ country: "NL", zone: "Europe/Amsterdam" }),
  Object.freeze({ country: "NO", zone: "Europe/Oslo" }),
  Object.freeze({ country: "NP", zone: "Asia/Kathmandu" }),
  Object.freeze({ country: "NR", zone: "Pacific/Nauru" }),
  Object.freeze({ country: "NU", zone: "Pacific/Niue" }),
  Object.freeze({ country: "NZ", zone: "Pacific/Auckland" }),
  Object.freeze({ country: "NZ", zone: "Pacific/Chatham" }),
  Object.freeze({ country: "OM", zone: "Asia/Muscat" }),
  Object.freeze({ country: "PA", zone: "America/Panama" }),
  Object.freeze({ country: "PE", zone: "America/Lima" }),
  Object.freeze({ country: "PF", zone: "Pacific/Tahiti" }),
  Object.freeze({ country: "PF", zone: "Pacific/Marquesas" }),
  Object.freeze({ country: "PF", zone: "Pacific/Gambier" }),
  Object.freeze({ country: "PG", zone: "Pacific/Port_Moresby" }),
  Object.freeze({ country: "PG", zone: "Pacific/Bougainville" }),
  Object.freeze({ country: "PH", zone: "Asia/Manila" }),
  Object.freeze({ country: "PK", zone: "Asia/Karachi" }),
  Object.freeze({ country: "PL", zone: "Europe/Warsaw" }),
  Object.freeze({ country: "PM", zone: "America/Miquelon" }),
  Object.freeze({ country: "PN", zone: "Pacific/Pitcairn" }),
  Object.freeze({ country: "PR", zone: "America/Puerto_Rico" }),
  Object.freeze({ country: "PS", zone: "Asia/Gaza" }),
  Object.freeze({ country: "PS", zone: "Asia/Hebron" }),
  Object.freeze({ country: "PT", zone: "Europe/Lisbon" }),
  Object.freeze({ country: "PT", zone: "Atlantic/Madeira" }),
  Object.freeze({ country: "PT", zone: "Atlantic/Azores" }),
  Object.freeze({ country: "PW", zone: "Pacific/Palau" }),
  Object.freeze({ country: "PY", zone: "America/Asuncion" }),
  Object.freeze({ country: "QA", zone: "Asia/Qatar" }),
  Object.freeze({ country: "RE", zone: "Indian/Reunion" }),
  Object.freeze({ country: "RO", zone: "Europe/Bucharest" }),
  Object.freeze({ country: "RS", zone: "Europe/Belgrade" }),
  Object.freeze({ country: "RU", zone: "Europe/Kaliningrad" }),
  Object.freeze({ country: "RU", zone: "Europe/Moscow" }),
  Object.freeze({ country: "UA", zone: "Europe/Simferopol" }),
  Object.freeze({ country: "RU", zone: "Europe/Kirov" }),
  Object.freeze({ country: "RU", zone: "Europe/Volgograd" }),
  Object.freeze({ country: "RU", zone: "Europe/Astrakhan" }),
  Object.freeze({ country: "RU", zone: "Europe/Saratov" }),
  Object.freeze({ country: "RU", zone: "Europe/Ulyanovsk" }),
  Object.freeze({ country: "RU", zone: "Europe/Samara" }),
  Object.freeze({ country: "RU", zone: "Asia/Yekaterinburg" }),
  Object.freeze({ country: "RU", zone: "Asia/Omsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Novosibirsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Barnaul" }),
  Object.freeze({ country: "RU", zone: "Asia/Tomsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Novokuznetsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Krasnoyarsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Irkutsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Chita" }),
  Object.freeze({ country: "RU", zone: "Asia/Yakutsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Khandyga" }),
  Object.freeze({ country: "RU", zone: "Asia/Vladivostok" }),
  Object.freeze({ country: "RU", zone: "Asia/Ust-Nera" }),
  Object.freeze({ country: "RU", zone: "Asia/Magadan" }),
  Object.freeze({ country: "RU", zone: "Asia/Sakhalin" }),
  Object.freeze({ country: "RU", zone: "Asia/Srednekolymsk" }),
  Object.freeze({ country: "RU", zone: "Asia/Kamchatka" }),
  Object.freeze({ country: "RU", zone: "Asia/Anadyr" }),
  Object.freeze({ country: "RW", zone: "Africa/Kigali" }),
  Object.freeze({ country: "SA", zone: "Asia/Riyadh" }),
  Object.freeze({ country: "SB", zone: "Pacific/Guadalcanal" }),
  Object.freeze({ country: "SC", zone: "Indian/Mahe" }),
  Object.freeze({ country: "SD", zone: "Africa/Khartoum" }),
  Object.freeze({ country: "SE", zone: "Europe/Stockholm" }),
  Object.freeze({ country: "SG", zone: "Asia/Singapore" }),
  Object.freeze({ country: "SH", zone: "Atlantic/St_Helena" }),
  Object.freeze({ country: "SI", zone: "Europe/Ljubljana" }),
  Object.freeze({ country: "SJ", zone: "Arctic/Longyearbyen" }),
  Object.freeze({ country: "SK", zone: "Europe/Bratislava" }),
  Object.freeze({ country: "SL", zone: "Africa/Freetown" }),
  Object.freeze({ country: "SM", zone: "Europe/San_Marino" }),
  Object.freeze({ country: "SN", zone: "Africa/Dakar" }),
  Object.freeze({ country: "SO", zone: "Africa/Mogadishu" }),
  Object.freeze({ country: "SR", zone: "America/Paramaribo" }),
  Object.freeze({ country: "SS", zone: "Africa/Juba" }),
  Object.freeze({ country: "ST", zone: "Africa/Sao_Tome" }),
  Object.freeze({ country: "SV", zone: "America/El_Salvador" }),
  Object.freeze({ country: "SX", zone: "America/Lower_Princes" }),
  Object.freeze({ country: "SY", zone: "Asia/Damascus" }),
  Object.freeze({ country: "SZ", zone: "Africa/Mbabane" }),
  Object.freeze({ country: "TC", zone: "America/Grand_Turk" }),
  Object.freeze({ country: "TD", zone: "Africa/Ndjamena" }),
  Object.freeze({ country: "TF", zone: "Indian/Kerguelen" }),
  Object.freeze({ country: "TG", zone: "Africa/Lome" }),
  Object.freeze({ country: "TH", zone: "Asia/Bangkok" }),
  Object.freeze({ country: "TJ", zone: "Asia/Dushanbe" }),
  Object.freeze({ country: "TK", zone: "Pacific/Fakaofo" }),
  Object.freeze({ country: "TL", zone: "Asia/Dili" }),
  Object.freeze({ country: "TM", zone: "Asia/Ashgabat" }),
  Object.freeze({ country: "TN", zone: "Africa/Tunis" }),
  Object.freeze({ country: "TO", zone: "Pacific/Tongatapu" }),
  Object.freeze({ country: "TR", zone: "Europe/Istanbul" }),
  Object.freeze({ country: "TT", zone: "America/Port_of_Spain" }),
  Object.freeze({ country: "TV", zone: "Pacific/Funafuti" }),
  Object.freeze({ country: "TW", zone: "Asia/Taipei" }),
  Object.freeze({ country: "TZ", zone: "Africa/Dar_es_Salaam" }),
  Object.freeze({ country: "UA", zone: "Europe/Kyiv" }),
  Object.freeze({ country: "UG", zone: "Africa/Kampala" }),
  Object.freeze({ country: "UM", zone: "Pacific/Midway" }),
  Object.freeze({ country: "UM", zone: "Pacific/Wake" }),
  Object.freeze({ country: "US", zone: "America/New_York" }),
  Object.freeze({ country: "US", zone: "America/Detroit" }),
  Object.freeze({ country: "US", zone: "America/Kentucky/Louisville" }),
  Object.freeze({ country: "US", zone: "America/Kentucky/Monticello" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Indianapolis" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Vincennes" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Winamac" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Marengo" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Petersburg" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Vevay" }),
  Object.freeze({ country: "US", zone: "America/Chicago" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Tell_City" }),
  Object.freeze({ country: "US", zone: "America/Indiana/Knox" }),
  Object.freeze({ country: "US", zone: "America/Menominee" }),
  Object.freeze({ country: "US", zone: "America/North_Dakota/Center" }),
  Object.freeze({ country: "US", zone: "America/North_Dakota/New_Salem" }),
  Object.freeze({ country: "US", zone: "America/North_Dakota/Beulah" }),
  Object.freeze({ country: "US", zone: "America/Denver" }),
  Object.freeze({ country: "US", zone: "America/Boise" }),
  Object.freeze({ country: "US", zone: "America/Phoenix" }),
  Object.freeze({ country: "US", zone: "America/Los_Angeles" }),
  Object.freeze({ country: "US", zone: "America/Anchorage" }),
  Object.freeze({ country: "US", zone: "America/Juneau" }),
  Object.freeze({ country: "US", zone: "America/Sitka" }),
  Object.freeze({ country: "US", zone: "America/Metlakatla" }),
  Object.freeze({ country: "US", zone: "America/Yakutat" }),
  Object.freeze({ country: "US", zone: "America/Nome" }),
  Object.freeze({ country: "US", zone: "America/Adak" }),
  Object.freeze({ country: "US", zone: "Pacific/Honolulu" }),
  Object.freeze({ country: "UY", zone: "America/Montevideo" }),
  Object.freeze({ country: "UZ", zone: "Asia/Samarkand" }),
  Object.freeze({ country: "UZ", zone: "Asia/Tashkent" }),
  Object.freeze({ country: "VA", zone: "Europe/Vatican" }),
  Object.freeze({ country: "VC", zone: "America/St_Vincent" }),
  Object.freeze({ country: "VE", zone: "America/Caracas" }),
  Object.freeze({ country: "VG", zone: "America/Tortola" }),
  Object.freeze({ country: "VI", zone: "America/St_Thomas" }),
  Object.freeze({ country: "VN", zone: "Asia/Ho_Chi_Minh" }),
  Object.freeze({ country: "VU", zone: "Pacific/Efate" }),
  Object.freeze({ country: "WF", zone: "Pacific/Wallis" }),
  Object.freeze({ country: "WS", zone: "Pacific/Apia" }),
  Object.freeze({ country: "YE", zone: "Asia/Aden" }),
  Object.freeze({ country: "YT", zone: "Indian/Mayotte" }),
  Object.freeze({ country: "ZA", zone: "Africa/Johannesburg" }),
  Object.freeze({ country: "ZM", zone: "Africa/Lusaka" }),
  Object.freeze({ country: "ZW", zone: "Africa/Harare" }),
]);

// Fixed Japanese labels keep region names consistent across browsers and devices.
window.TIME_ZONE_NAMES_JA = Object.freeze({
  "Europe/Andorra": "アンドラ",
  "Asia/Dubai": "アラブ首長国連邦",
  "Asia/Kabul": "アフガニスタン",
  "America/Antigua": "アンティグア・バーブーダ",
  "America/Anguilla": "アンギラ",
  "Europe/Tirane": "アルバニア",
  "Asia/Yerevan": "アルメニア",
  "Africa/Luanda": "アンゴラ",
  "Antarctica/McMurdo": "マクマード基地",
  "Antarctica/Casey": "ケーシー基地",
  "Antarctica/Davis": "デービス基地",
  "Antarctica/DumontDUrville": "デュモン・デュルヴィル基地",
  "Antarctica/Mawson": "モーソン基地",
  "Antarctica/Palmer": "パーマー基地",
  "Antarctica/Rothera": "ロゼラ基地",
  "Antarctica/Syowa": "昭和基地",
  "Antarctica/Troll": "トロル基地",
  "Antarctica/Vostok": "ボストーク基地",
  "America/Argentina/Buenos_Aires": "ブエノスアイレス",
  "America/Argentina/Cordoba": "コルドバ",
  "America/Argentina/Salta": "サルタ",
  "America/Argentina/Jujuy": "フフイ",
  "America/Argentina/Tucuman": "トゥクマン",
  "America/Argentina/Catamarca": "カタマルカ",
  "America/Argentina/La_Rioja": "ラリオハ",
  "America/Argentina/San_Juan": "サンファン",
  "America/Argentina/Mendoza": "メンドーサ",
  "America/Argentina/San_Luis": "サンルイス",
  "America/Argentina/Rio_Gallegos": "リオガジェゴス",
  "America/Argentina/Ushuaia": "ウシュアイア",
  "Pacific/Pago_Pago": "米領サモア",
  "Europe/Vienna": "オーストリア",
  "Australia/Lord_Howe": "ロードハウ",
  "Antarctica/Macquarie": "マッコリー",
  "Australia/Hobart": "ホバート",
  "Australia/Melbourne": "メルボルン",
  "Australia/Sydney": "シドニー",
  "Australia/Broken_Hill": "ブロークンヒル",
  "Australia/Brisbane": "ブリスベン",
  "Australia/Lindeman": "リンデマン",
  "Australia/Adelaide": "アデレード",
  "Australia/Darwin": "ダーウィン",
  "Australia/Perth": "パース",
  "Australia/Eucla": "ユークラ",
  "America/Aruba": "アルバ",
  "Europe/Mariehamn": "オーランド諸島",
  "Asia/Baku": "アゼルバイジャン",
  "Europe/Sarajevo": "ボスニア・ヘルツェゴビナ",
  "America/Barbados": "バルバドス",
  "Asia/Dhaka": "バングラデシュ",
  "Europe/Brussels": "ベルギー",
  "Africa/Ouagadougou": "ブルキナファソ",
  "Europe/Sofia": "ブルガリア",
  "Asia/Bahrain": "バーレーン",
  "Africa/Bujumbura": "ブルンジ",
  "Africa/Porto-Novo": "ベナン",
  "America/St_Barthelemy": "サン・バルテルミー",
  "Atlantic/Bermuda": "バミューダ",
  "Asia/Brunei": "ブルネイ",
  "America/La_Paz": "ボリビア",
  "America/Kralendijk": "オランダ領カリブ",
  "America/Noronha": "ノローニャ",
  "America/Belem": "ベレン",
  "America/Fortaleza": "フォルタレザ",
  "America/Recife": "レシフェ",
  "America/Araguaina": "アラグァイナ",
  "America/Maceio": "マセイオ",
  "America/Bahia": "バイーア",
  "America/Sao_Paulo": "サンパウロ",
  "America/Campo_Grande": "カンポグランデ",
  "America/Cuiaba": "クイアバ",
  "America/Santarem": "サンタレム",
  "America/Porto_Velho": "ポルトベーリョ",
  "America/Boa_Vista": "ボアビスタ",
  "America/Manaus": "マナウス",
  "America/Eirunepe": "エイルネペ",
  "America/Rio_Branco": "リオブランコ",
  "America/Nassau": "バハマ",
  "Asia/Thimphu": "ブータン",
  "Africa/Gaborone": "ボツワナ",
  "Europe/Minsk": "ベラルーシ",
  "America/Belize": "ベリーズ",
  "America/St_Johns": "セントジョンズ",
  "America/Halifax": "ハリファクス",
  "America/Glace_Bay": "グレースベイ",
  "America/Moncton": "モンクトン",
  "America/Goose_Bay": "グースベイ",
  "America/Blanc-Sablon": "ブラン・サブロン",
  "America/Toronto": "トロント",
  "America/Iqaluit": "イカルイット",
  "America/Atikokan": "アティコカン",
  "America/Winnipeg": "ウィニペグ",
  "America/Resolute": "レゾリュート",
  "America/Rankin_Inlet": "ランキンインレット",
  "America/Regina": "レジャイナ",
  "America/Swift_Current": "スウィフトカレント",
  "America/Edmonton": "エドモントン",
  "America/Cambridge_Bay": "ケンブリッジベイ",
  "America/Inuvik": "イヌヴィク",
  "America/Creston": "クレストン",
  "America/Dawson_Creek": "ドーソンクリーク",
  "America/Fort_Nelson": "フォートネルソン",
  "America/Whitehorse": "ホワイトホース",
  "America/Dawson": "ドーソン",
  "America/Vancouver": "バンクーバー",
  "Indian/Cocos": "ココス(キーリング)諸島",
  "Africa/Kinshasa": "キンシャサ",
  "Africa/Lubumbashi": "ルブンバシ",
  "Africa/Bangui": "中央アフリカ共和国",
  "Africa/Brazzaville": "コンゴ共和国(ブラザビル)",
  "Europe/Zurich": "スイス",
  "Africa/Abidjan": "コートジボワール",
  "Pacific/Rarotonga": "クック諸島",
  "America/Santiago": "チリ",
  "America/Coyhaique": "コジャイケ",
  "America/Punta_Arenas": "プンタアレナス",
  "Pacific/Easter": "イースター島",
  "Africa/Douala": "カメルーン",
  "Asia/Shanghai": "中国",
  "Asia/Urumqi": "ウルムチ",
  "America/Bogota": "コロンビア",
  "America/Costa_Rica": "コスタリカ",
  "America/Havana": "キューバ",
  "Atlantic/Cape_Verde": "カーボベルデ",
  "America/Curacao": "キュラソー",
  "Indian/Christmas": "クリスマス島",
  "Asia/Nicosia": "ニコシア",
  "Asia/Famagusta": "ファマグスタ",
  "Europe/Prague": "チェコ",
  "Europe/Berlin": "ドイツ",
  "Europe/Busingen": "ビュージンゲン",
  "Africa/Djibouti": "ジブチ",
  "Europe/Copenhagen": "デンマーク",
  "America/Dominica": "ドミニカ国",
  "America/Santo_Domingo": "ドミニカ共和国",
  "Africa/Algiers": "アルジェリア",
  "America/Guayaquil": "エクアドル",
  "Pacific/Galapagos": "ガラパゴス",
  "Europe/Tallinn": "エストニア",
  "Africa/Cairo": "エジプト",
  "Africa/El_Aaiun": "西サハラ",
  "Africa/Asmara": "エリトリア",
  "Europe/Madrid": "スペイン",
  "Africa/Ceuta": "セウタ",
  "Atlantic/Canary": "カナリア",
  "Africa/Addis_Ababa": "エチオピア",
  "Europe/Helsinki": "フィンランド",
  "Pacific/Fiji": "フィジー",
  "Atlantic/Stanley": "フォークランド諸島",
  "Pacific/Chuuk": "チューク",
  "Pacific/Pohnpei": "ポンペイ島",
  "Pacific/Kosrae": "コスラエ",
  "Atlantic/Faroe": "フェロー諸島",
  "Europe/Paris": "フランス",
  "Africa/Libreville": "ガボン",
  "Europe/London": "イギリス",
  "America/Grenada": "グレナダ",
  "Asia/Tbilisi": "ジョージア",
  "America/Cayenne": "仏領ギアナ",
  "Europe/Guernsey": "ガーンジー",
  "Africa/Accra": "ガーナ",
  "Europe/Gibraltar": "ジブラルタル",
  "America/Nuuk": "ヌーク",
  "America/Danmarkshavn": "デンマークシャウン",
  "America/Scoresbysund": "イトコルトルミット",
  "America/Thule": "チューレ",
  "Africa/Banjul": "ガンビア",
  "Africa/Conakry": "ギニア",
  "America/Guadeloupe": "グアドループ",
  "Africa/Malabo": "赤道ギニア",
  "Europe/Athens": "ギリシャ",
  "Atlantic/South_Georgia": "サウスジョージア・サウスサンドウィッチ諸島",
  "America/Guatemala": "グアテマラ",
  "Pacific/Guam": "グアム",
  "Africa/Bissau": "ギニアビサウ",
  "America/Guyana": "ガイアナ",
  "Asia/Hong_Kong": "中華人民共和国香港特別行政区",
  "America/Tegucigalpa": "ホンジュラス",
  "Europe/Zagreb": "クロアチア",
  "America/Port-au-Prince": "ハイチ",
  "Europe/Budapest": "ハンガリー",
  "Asia/Jakarta": "ジャカルタ",
  "Asia/Pontianak": "ポンティアナック",
  "Asia/Makassar": "マカッサル",
  "Asia/Jayapura": "ジャヤプラ",
  "Europe/Dublin": "アイルランド",
  "Asia/Jerusalem": "イスラエル",
  "Europe/Isle_of_Man": "マン島",
  "Asia/Kolkata": "インド",
  "Indian/Chagos": "英領インド洋地域",
  "Asia/Baghdad": "イラク",
  "Asia/Tehran": "イラン",
  "Atlantic/Reykjavik": "アイスランド",
  "Europe/Rome": "イタリア",
  "Europe/Jersey": "ジャージー",
  "America/Jamaica": "ジャマイカ",
  "Asia/Amman": "ヨルダン",
  "Asia/Tokyo": "東京",
  "Africa/Nairobi": "ケニア",
  "Asia/Bishkek": "キルギス",
  "Asia/Phnom_Penh": "カンボジア",
  "Pacific/Tarawa": "タラワ",
  "Pacific/Kanton": "カントン島",
  "Pacific/Kiritimati": "キリスィマスィ島",
  "Indian/Comoro": "コモロ",
  "America/St_Kitts": "セントクリストファー・ネーヴィス",
  "Asia/Pyongyang": "北朝鮮",
  "Asia/Seoul": "韓国",
  "Asia/Kuwait": "クウェート",
  "America/Cayman": "ケイマン諸島",
  "Asia/Almaty": "アルマトイ",
  "Asia/Qyzylorda": "クズロルダ",
  "Asia/Qostanay": "コスタナイ",
  "Asia/Aqtobe": "アクトベ",
  "Asia/Aqtau": "アクタウ",
  "Asia/Atyrau": "アティラウ",
  "Asia/Oral": "オラル",
  "Asia/Vientiane": "ラオス",
  "Asia/Beirut": "レバノン",
  "America/St_Lucia": "セントルシア",
  "Europe/Vaduz": "リヒテンシュタイン",
  "Asia/Colombo": "スリランカ",
  "Africa/Monrovia": "リベリア",
  "Africa/Maseru": "レソト",
  "Europe/Vilnius": "リトアニア",
  "Europe/Luxembourg": "ルクセンブルク",
  "Europe/Riga": "ラトビア",
  "Africa/Tripoli": "リビア",
  "Africa/Casablanca": "モロッコ",
  "Europe/Monaco": "モナコ",
  "Europe/Chisinau": "モルドバ",
  "Europe/Podgorica": "モンテネグロ",
  "America/Marigot": "サン・マルタン",
  "Indian/Antananarivo": "マダガスカル",
  "Pacific/Majuro": "マーシャル諸島",
  "Pacific/Kwajalein": "クェゼリン",
  "Europe/Skopje": "北マケドニア",
  "Africa/Bamako": "マリ",
  "Asia/Yangon": "ミャンマー (ビルマ)",
  "Asia/Ulaanbaatar": "ウランバートル",
  "Asia/Hovd": "ホブド",
  "Asia/Macau": "中華人民共和国マカオ特別行政区",
  "Pacific/Saipan": "北マリアナ諸島",
  "America/Martinique": "マルティニーク",
  "Africa/Nouakchott": "モーリタニア",
  "America/Montserrat": "モントセラト",
  "Europe/Malta": "マルタ",
  "Indian/Mauritius": "モーリシャス",
  "Indian/Maldives": "モルディブ",
  "Africa/Blantyre": "マラウイ",
  "America/Mexico_City": "メキシコシティー",
  "America/Cancun": "カンクン",
  "America/Merida": "メリダ",
  "America/Monterrey": "モンテレイ",
  "America/Matamoros": "マタモロス",
  "America/Chihuahua": "チワワ",
  "America/Ciudad_Juarez": "シウダー・フアレス",
  "America/Ojinaga": "オヒナガ",
  "America/Mazatlan": "マサトラン",
  "America/Bahia_Banderas": "バイアバンデラ",
  "America/Hermosillo": "エルモシヨ",
  "America/Tijuana": "ティフアナ",
  "Asia/Kuala_Lumpur": "マレーシア",
  "Asia/Kuching": "クチン",
  "Africa/Maputo": "モザンビーク",
  "Africa/Windhoek": "ナミビア",
  "Pacific/Noumea": "ニューカレドニア",
  "Africa/Niamey": "ニジェール",
  "Pacific/Norfolk": "ノーフォーク島",
  "Africa/Lagos": "ナイジェリア",
  "America/Managua": "ニカラグア",
  "Europe/Amsterdam": "オランダ",
  "Europe/Oslo": "ノルウェー",
  "Asia/Kathmandu": "ネパール",
  "Pacific/Nauru": "ナウル",
  "Pacific/Niue": "ニウエ",
  "Pacific/Auckland": "ニュージーランド",
  "Pacific/Chatham": "チャタム",
  "Asia/Muscat": "オマーン",
  "America/Panama": "パナマ",
  "America/Lima": "ペルー",
  "Pacific/Tahiti": "タヒチ",
  "Pacific/Marquesas": "マルキーズ",
  "Pacific/Gambier": "ガンビエ諸島",
  "Pacific/Port_Moresby": "ポートモレスビー",
  "Pacific/Bougainville": "ブーゲンビル",
  "Asia/Manila": "フィリピン",
  "Asia/Karachi": "パキスタン",
  "Europe/Warsaw": "ポーランド",
  "America/Miquelon": "サンピエール島・ミクロン島",
  "Pacific/Pitcairn": "ピトケアン諸島",
  "America/Puerto_Rico": "プエルトリコ",
  "Asia/Gaza": "ガザ",
  "Asia/Hebron": "ヘブロン",
  "Europe/Lisbon": "ポルトガル",
  "Atlantic/Madeira": "マデイラ",
  "Atlantic/Azores": "アゾレス",
  "Pacific/Palau": "パラオ",
  "America/Asuncion": "パラグアイ",
  "Asia/Qatar": "カタール",
  "Indian/Reunion": "レユニオン",
  "Europe/Bucharest": "ルーマニア",
  "Europe/Belgrade": "セルビア",
  "Europe/Kaliningrad": "カリーニングラード",
  "Europe/Moscow": "モスクワ",
  "Europe/Simferopol": "シンフェロポリ",
  "Europe/Kirov": "キーロフ",
  "Europe/Volgograd": "ボルゴグラード",
  "Europe/Astrakhan": "アストラハン",
  "Europe/Saratov": "サラトフ",
  "Europe/Ulyanovsk": "ウリヤノフスク",
  "Europe/Samara": "サマラ",
  "Asia/Yekaterinburg": "エカテリンブルグ",
  "Asia/Omsk": "オムスク",
  "Asia/Novosibirsk": "ノヴォシビルスク",
  "Asia/Barnaul": "バルナウル",
  "Asia/Tomsk": "トムスク",
  "Asia/Novokuznetsk": "ノヴォクズネツク",
  "Asia/Krasnoyarsk": "クラスノヤルスク",
  "Asia/Irkutsk": "イルクーツク",
  "Asia/Chita": "チタ",
  "Asia/Yakutsk": "ヤクーツク",
  "Asia/Khandyga": "ハンドゥイガ",
  "Asia/Vladivostok": "ウラジオストク",
  "Asia/Ust-Nera": "ウスチネラ",
  "Asia/Magadan": "マガダン",
  "Asia/Sakhalin": "サハリン",
  "Asia/Srednekolymsk": "スレドネコリムスク",
  "Asia/Kamchatka": "カムチャッカ",
  "Asia/Anadyr": "アナディリ",
  "Africa/Kigali": "ルワンダ",
  "Asia/Riyadh": "サウジアラビア",
  "Pacific/Guadalcanal": "ソロモン諸島",
  "Indian/Mahe": "セーシェル",
  "Africa/Khartoum": "スーダン",
  "Europe/Stockholm": "スウェーデン",
  "Asia/Singapore": "シンガポール",
  "Atlantic/St_Helena": "セントヘレナ",
  "Europe/Ljubljana": "スロベニア",
  "Arctic/Longyearbyen": "スバールバル諸島・ヤンマイエン島",
  "Europe/Bratislava": "スロバキア",
  "Africa/Freetown": "シエラレオネ",
  "Europe/San_Marino": "サンマリノ",
  "Africa/Dakar": "セネガル",
  "Africa/Mogadishu": "ソマリア",
  "America/Paramaribo": "スリナム",
  "Africa/Juba": "南スーダン",
  "Africa/Sao_Tome": "サントメ・プリンシペ",
  "America/El_Salvador": "エルサルバドル",
  "America/Lower_Princes": "シント・マールテン",
  "Asia/Damascus": "シリア",
  "Africa/Mbabane": "エスワティニ",
  "America/Grand_Turk": "タークス・カイコス諸島",
  "Africa/Ndjamena": "チャド",
  "Indian/Kerguelen": "仏領極南諸島",
  "Africa/Lome": "トーゴ",
  "Asia/Bangkok": "タイ",
  "Asia/Dushanbe": "タジキスタン",
  "Pacific/Fakaofo": "トケラウ",
  "Asia/Dili": "東ティモール",
  "Asia/Ashgabat": "トルクメニスタン",
  "Africa/Tunis": "チュニジア",
  "Pacific/Tongatapu": "トンガ",
  "Europe/Istanbul": "トルコ",
  "America/Port_of_Spain": "トリニダード・トバゴ",
  "Pacific/Funafuti": "ツバル",
  "Asia/Taipei": "台湾",
  "Africa/Dar_es_Salaam": "タンザニア",
  "Europe/Kyiv": "ウクライナ",
  "Africa/Kampala": "ウガンダ",
  "Pacific/Midway": "ミッドウェー島",
  "Pacific/Wake": "ウェーク島",
  "America/New_York": "ニューヨーク",
  "America/Detroit": "デトロイト",
  "America/Kentucky/Louisville": "ルイビル",
  "America/Kentucky/Monticello": "ケンタッキー州モンティチェロ",
  "America/Indiana/Indianapolis": "インディアナポリス",
  "America/Indiana/Vincennes": "インディアナ州ビンセンス",
  "America/Indiana/Winamac": "インディアナ州ウィナマック",
  "America/Indiana/Marengo": "インディアナ州マレンゴ",
  "America/Indiana/Petersburg": "インディアナ州ピーターズバーグ",
  "America/Indiana/Vevay": "インディアナ州ビベー",
  "America/Chicago": "シカゴ",
  "America/Indiana/Tell_City": "インディアナ州テルシティ",
  "America/Indiana/Knox": "インディアナ州ノックス",
  "America/Menominee": "メノミニー",
  "America/North_Dakota/Center": "ノースダコタ州センター",
  "America/North_Dakota/New_Salem": "ノースダコタ州ニューセーラム",
  "America/North_Dakota/Beulah": "ノースダコタ州ビューラー",
  "America/Denver": "デンバー",
  "America/Boise": "ボイシ",
  "America/Phoenix": "フェニックス",
  "America/Los_Angeles": "ロサンゼルス",
  "America/Anchorage": "アンカレッジ",
  "America/Juneau": "ジュノー",
  "America/Sitka": "シトカ",
  "America/Metlakatla": "メトラカトラ",
  "America/Yakutat": "ヤクタット",
  "America/Nome": "ノーム",
  "America/Adak": "アダック",
  "Pacific/Honolulu": "ホノルル",
  "America/Montevideo": "ウルグアイ",
  "Asia/Samarkand": "サマルカンド",
  "Asia/Tashkent": "ウズベキスタン",
  "Europe/Vatican": "バチカン市国",
  "America/St_Vincent": "セントビンセント及びグレナディーン諸島",
  "America/Caracas": "ベネズエラ",
  "America/Tortola": "英領ヴァージン諸島",
  "America/St_Thomas": "米領ヴァージン諸島",
  "Asia/Ho_Chi_Minh": "ベトナム",
  "Pacific/Efate": "バヌアツ",
  "Pacific/Wallis": "ウォリス・フツナ",
  "Pacific/Apia": "サモア",
  "Asia/Aden": "イエメン",
  "Indian/Mayotte": "マヨット",
  "Africa/Johannesburg": "南アフリカ",
  "Africa/Lusaka": "ザンビア",
  "Africa/Harare": "ジンバブエ"
});
